# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = "ï„ "
"kitty" = "ï„ "
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"file manager" = "ï¼"
"thunar" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"gedit" = "ïœ˜"
"libreoffice" = "ï£…"
"nvim" = "îŸ…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"wofi" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ïœ¤"
"spotify" = "ï†¼"
"jetbrains-idea" = "ï„¡"
"brave-browser" = "ï¦˜"
"Signal" = "ï‚•"
"signal" = "ï‚•"
"an-anime-game-launcher" = "ï„›"
"Genshin Impact" = "ï„›"
"genshin-impact" = "ï„›"
"wine" = "ï„›"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
separator = ": "
